### ISSUE TITLE
README URLs invalid

### ISSUE THREAD

**Issue by ghost** [go-toolsmith/pkgload#22]
module is named as:

https://github.com/go-toolsmith/pkgload/blob/30b1077b703127b59b8cd304bf2adc9117c3330d/go.mod#L1

but all of the links are invalid:

https://github.com/go-toolsmith/pkgload/blob/30b1077b703127b59b8cd304bf2adc9117c3330d/README.md?plain=1#L58-L65

**Comment by cristaloleg** [comment]
Hi, nice catch! Feel free to make a PR (or I will do tomorrow, well, in 7h or so). Thanks!
