### ISSUE TITLE
Assertion failure for github.com/docopt/docopt-go/examples/unit_test

### ISSUE THREAD

**Issue by quasilyte** [go-toolsmith/pkgload#5]
```
2019/01/11 18:46:44 ERROR: exit status 2: panic: nil assertion failed for ID="github.com/docopt/docopt-go/examples/unit_test [github.com/docopt/docopt-go/examples/unit_test.test]" Path="github.com/docopt/docopt-go/examples/unit_test"
```

**Comment by a-urth** [comment]
Also interested in this, since this package is used in `github.com/Quasilyte/go-consistent`.
Whats the exact expectations of `pkgload` to be nil here?

**Comment by cristaloleg** [comment]
The panic triggers here https://github.com/go-toolsmith/pkgload/blob/master/pkgload.go#L100

Sadly I don't have a context atm why it should be nil here.

**Comment by quasilyte** [comment]
I'll dig on it soon, no worries. :)

**Comment by quasilyte** [comment]
Reproduced in isolation.
Will try to fix it today.

--- Update

Oh, I see.
Seems like it fails if package name itself is in for of `blah_test`.
Currently, it supposed that `_test` suffix is used for external tests.
Will think about a better way to resolve this ambiguity.

**Comment by quasilyte** [comment]
Problematic package `github.com/docopt/docopt-go/examples/unit_test` now loads without a panic.

@a-urth can you confirm that one of the packages that caused the panic had either of these in their package path?
- `.test` suffix, like `github.com/foo/bar.test`
- `_test` suffix, like `github.com/foo/bar_test`

If yes, then the problem should be solved by now.
If no, please provide a path example here, or give a reference to a repo (if it's possible).

**Comment by a-urth** [comment]
@Quasilyte for me yes, it was because of presence of folder with "_test" suffix.
In code its clear that loader checks for that particular kind of folders and expects something to be nil. I just didn't know what exactly.
